name: Trytiole

on:
  push:
    branches:
      - main

jobs:
  sentry_release:
    name: Sentry release
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - name: Sentry Release 
        uses: photonbit/sentrytry@main
        with:
          sentry_project: sentrytry
          sentry_environment: 'staging'
        env:
          SENTRY_ORG: 'daniel-moreno-medina'
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_RELEASE: ${{ github.sha }}